#!/bin/bash

# Setup Uptime Kuma monitor for Lab Gate
# This script creates an HTTP(s) JSON monitor for the Lab Gate endpoint

KUMA_URL="http://localhost:3001"
MONITOR_NAME="Lab Gate"
MONITOR_URL="http://99.76.234.25:5056/lab/gate/status"

echo "Setting up Uptime Kuma monitor for Lab Gate..."
echo "Monitor Name: $MONITOR_NAME"
echo "Monitor URL: $MONITOR_URL"
echo ""
echo "Monitor Configuration:"
echo "- Type: HTTP(s) - Json Query"
echo "- Method: GET"
echo "- Heartbeat Interval: 60 seconds"
echo "- Max Retries: 2"
echo "- JSON Path: ok"
echo "- Expected Value: true"
echo ""
echo "Please configure this monitor manually in Uptime Kuma at: $KUMA_URL"
echo ""
echo "Steps:"
echo "1. Open Uptime Kuma: $KUMA_URL"
echo "2. Click 'Add New Monitor'"
echo "3. Select Monitor Type: 'HTTP(s) - Json Query'"
echo "4. Enter:"
echo "   - Friendly Name: $MONITOR_NAME"
echo "   - URL: $MONITOR_URL"
echo "   - JSON Path: ok"
echo "   - Expected Value: true"
echo "   - Heartbeat Interval: 60"
echo "   - Max Retries: 2"
echo "5. Add notification channels if configured"
echo "6. Save the monitor"
echo ""
echo "The monitor will:"
echo "- Check every 60 seconds"
echo "- Expect JSON response with ok=true"
echo "- Alert when ok=false or endpoint is unreachable"
echo ""
echo "Test the endpoint manually:"
echo "curl -s $MONITOR_URL | jq '.ok'"