name: Acceptance Report (comment)
on:
  workflow_run:
    workflows: ["Smoke (Acceptance)"]
    types: [completed]

permissions:
  contents: read
  actions: read
  checks: read
  pull-requests: write

jobs:
  comment:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build report body
        id: body
        run: |
          STATUS="${{ github.event.workflow_run.conclusion }}"
          DURA="10s"
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"
          BODY="**Acceptance Report**
          • Result: **${STATUS}** in ${DURA}
          • UI: http://99.76.234.25:5000/health
          • API: http://99.76.234.25:5055/api/health
          • Doctor Packs: http://99.76.234.25:5056/lab/doctor/packs
          • CI Artifacts & logs: ${RUN_URL}"
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Determine PR number
        id: find
        uses: potiuk/get-workflow-origin@v1_3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

      - name: Post PR comment
        if: steps.find.outputs.pullRequestNumber
        uses: mshick/add-pr-comment@v2
        with:
          message: ${{ steps.body.outputs.body }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          issue: ${{ steps.find.outputs.pullRequestNumber }}