name: Acceptance Report (comment)
on:
  workflow_run:
    workflows: ["Smoke (Acceptance)"]
    types: [completed]

permissions:
  contents: read
  actions: read
  checks: read
  pull-requests: write

jobs:
  comment:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build report body
        id: body
        run: |
          STATUS="${{ github.event.workflow_run.conclusion }}"
          DURA="10s"
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"
          echo "body=**Acceptance Report**%0A• Result: **${STATUS}** in ${DURA}%0A• UI: http://99.76.234.25:5000/health%0A• API: http://99.76.234.25:5055/api/health%0A• Doctor Packs: http://99.76.234.25:5056/lab/doctor/packs%0A• CI Artifacts & logs: ${RUN_URL}" >> $GITHUB_OUTPUT

      - name: Determine PR number
        id: find
        uses: potiuk/get-workflow-origin@v1_3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post PR comment
        if: steps.find.outputs.pullRequestNumber
        uses: mshick/add-pr-comment@v2
        with:
          message: ${{ steps.body.outputs.body }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          issue: ${{ steps.find.outputs.pullRequestNumber }}