name: Smoke (Acceptance)

on:
  pull_request:
    branches: [ lab ]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TARGET_HOST: 127.0.0.1
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_RUN_ID: ${{ github.run_id }}
      GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Prepare acceptance directory
        run: |
          set -e
          rm -rf storage
          mkdir -p storage/acceptance

      - name: Run smoke against public server
        run: node ops/tests/acceptance/smoke.mjs

      - name: Upload acceptance JSON
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: acceptance-latest
          path: storage/acceptance/latest.json
          retention-days: 7

      - name: Add success label
        if: success()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ready-to-merge

      - name: Add failure label
        if: failure()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: needs-investigation
